<?php

/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

$dictionary['tk_Financial_Info'] = array(
    'table' => 'tk_financial_info',
    'audited' => true,
    'activity_enabled' => false,
    'duplicate_merge' => true,
    'fields' =>  array (
        'disbursements' => 
        array (
          'required' => false,
          'readonly' => false,
          'name' => 'disbursements',
          'vname' => 'LBL_DISBURSEMENTS',
          'type' => 'varchar',
          'massupdate' => true,
          'hidemassupdate' => false,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'enabled',
          'duplicate_merge_dom_value' => '1',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'pii' => false,
          'default' => '',
          'full_text_search' => 
          array (
            'enabled' => '0',
            'boost' => '1',
            'searchable' => false,
          ),
          'calculated' => false,
          'len' => '255',
          'size' => '20',
        ),
        'disbursement_account' => 
        array (
          'required' => false,
          'readonly' => false,
          'name' => 'disbursement_account',
          'vname' => 'LBL_DISBURSEMENT_ACCOUNT',
          'type' => 'varchar',
          'massupdate' => true,
          'hidemassupdate' => false,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'enabled',
          'duplicate_merge_dom_value' => '1',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'pii' => false,
          'default' => '',
          'full_text_search' => 
          array (
            'enabled' => '0',
            'boost' => '1',
            'searchable' => false,
          ),
          'calculated' => false,
          'len' => '255',
          'size' => '20',
        ),
        'section' => 
        array (
          'required' => false,
          'readonly' => false,
          'name' => 'section',
          'vname' => 'LBL_SECTION',
          'type' => 'varchar',
          'massupdate' => true,
          'hidemassupdate' => false,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'enabled',
          'duplicate_merge_dom_value' => '1',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'pii' => false,
          'default' => '',
          'full_text_search' => 
          array (
            'enabled' => '0',
            'boost' => '1',
            'searchable' => false,
          ),
          'calculated' => false,
          'len' => '255',
          'size' => '20',
        ),
        'line_number' => 
        array (
          'required' => false,
          'readonly' => false,
          'name' => 'line_number',
          'vname' => 'LBL_LINE_NUMBER',
          'type' => 'int',
          'massupdate' => true,
          'hidemassupdate' => false,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'enabled',
          'duplicate_merge_dom_value' => '1',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'pii' => false,
          'default' => '',
          'full_text_search' => 
          array (
            'enabled' => '0',
            'boost' => '1',
            'searchable' => false,
          ),
          'calculated' => false,
          'len' => '11',
          'size' => '20',
          'enable_range_search' => false,
          'disable_num_format' => '',
          'min' => false,
          'max' => false,
        ),
        'payee_name' => 
        array (
          'required' => false,
          'readonly' => false,
          'name' => 'payee_name',
          'vname' => 'LBL_PAYEE_NAME',
          'type' => 'varchar',
          'massupdate' => true,
          'hidemassupdate' => false,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'enabled',
          'duplicate_merge_dom_value' => '1',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'pii' => false,
          'default' => '',
          'full_text_search' => 
          array (
            'enabled' => '0',
            'boost' => '1',
            'searchable' => false,
          ),
          'calculated' => false,
          'len' => '255',
          'size' => '20',
        ),
        'description_statement' => 
        array (
          'required' => false,
          'readonly' => false,
          'name' => 'description_statement',
          'vname' => 'LBL_DESCRIPTION_STATEMENT',
          'type' => 'text',
          'massupdate' => false,
          'hidemassupdate' => false,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'enabled',
          'duplicate_merge_dom_value' => '1',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'pii' => false,
          'default' => '',
          'full_text_search' => 
          array (
            'enabled' => '0',
            'boost' => '1',
            'searchable' => false,
          ),
          'calculated' => false,
          'size' => '20',
          'studio' => 'visible',
          'rows' => '4',
          'cols' => '20',
        ),
        'seller_amount' => 
        array (
          'required' => false,
          'readonly' => false,
          'name' => 'seller_amount',
          'vname' => 'LBL_SELLER_AMOUNT',
          'type' => 'currency',
          'massupdate' => false,
          'hidemassupdate' => false,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'enabled',
          'duplicate_merge_dom_value' => '1',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'pii' => false,
          'default' => 0.0,
          'calculated' => false,
          'len' => 26,
          'size' => '20',
          'enable_range_search' => false,
          'convertToBase' => true,
          'showTransactionalAmount' => true,
          'precision' => 6,
          'related_fields' => 
          array (
            0 => 'currency_id',
            1 => 'base_rate',
          ),
        ),
        'borrower_amount' => 
        array (
          'required' => false,
          'readonly' => false,
          'name' => 'borrower_amount',
          'vname' => 'LBL_BORROWER_AMOUNT',
          'type' => 'currency',
          'massupdate' => false,
          'hidemassupdate' => false,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'enabled',
          'duplicate_merge_dom_value' => '1',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'pii' => false,
          'default' => 0.0,
          'calculated' => false,
          'len' => 26,
          'size' => '20',
          'enable_range_search' => false,
          'convertToBase' => true,
          'showTransactionalAmount' => true,
          'precision' => 6,
          'related_fields' => 
          array (
            0 => 'currency_id',
            1 => 'base_rate',
          ),
        ),
        'payee_name_settlement' => 
        array (
          'required' => false,
          'readonly' => false,
          'name' => 'payee_name_settlement',
          'vname' => 'LBL_PAYEE_NAME_SETTLEMENT',
          'type' => 'varchar',
          'massupdate' => true,
          'hidemassupdate' => false,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'enabled',
          'duplicate_merge_dom_value' => '1',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'pii' => false,
          'default' => '',
          'full_text_search' => 
          array (
            'enabled' => '0',
            'boost' => '1',
            'searchable' => false,
          ),
          'calculated' => false,
          'len' => '255',
          'size' => '20',
        ),
        'order_number' => 
        array (
          'required' => false,
          'readonly' => false,
          'name' => 'order_number',
          'vname' => 'LBL_ORDER_NUMBER',
          'type' => 'varchar',
          'massupdate' => true,
          'hidemassupdate' => false,
          'no_default' => false,
          'comments' => '',
          'help' => '',
          'importable' => 'true',
          'duplicate_merge' => 'enabled',
          'duplicate_merge_dom_value' => '1',
          'audited' => false,
          'reportable' => true,
          'unified_search' => false,
          'merge_filter' => 'disabled',
          'pii' => false,
          'default' => '',
          'full_text_search' => 
          array (
            'enabled' => '0',
            'boost' => '1',
            'searchable' => false,
          ),
          'calculated' => false,
          'len' => '255',
          'size' => '20',
        ),
      ),
    'relationships' => array (
),
    'optimistic_locking' => true,
    'unified_search' => true,
    'full_text_search' => true,
);

if (!class_exists('VardefManager')){
}
VardefManager::createVardef('tk_Financial_Info','tk_Financial_Info', array('basic','team_security','assignable','taggable','sale'));
