<?php

/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

$dictionary['Party_RQ_Party'] = array(
    'table'              => 'party_rq_party',
    'audited'            => true,
    'activity_enabled'   => false,
    'duplicate_merge'    => true,
    'fields'             => array(
        'party_type'           => array(
            'required'                  => false,
            'name'                      => 'party_type',
            'vname'                     => 'LBL_PARTY_TYPE',
            'type'                      => 'enum',
            'massupdate'                => true,
            'no_default'                => false,
            'comments'                  => '',
            'help'                      => '',
            'importable'                => 'true',
            'duplicate_merge'           => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited'                   => false,
            'reportable'                => true,
            'unified_search'            => false,
            'merge_filter'              => 'disabled',
            'pii'                       => false,
            'default'                   => 'Agent',
            'calculated'                => false,
            'len'                       => 100,
            'size'                      => '20',
            'options'                   => 'qualia_role_list',
            'dependency'                => false,
        ),
        'parent_name'          => array(
            'required'                  => false,
            'source'                    => 'non-db',
            'name'                      => 'parent_name',
            'vname'                     => 'LBL_CHILD_ENTITY',
            'type'                      => 'parent',
            'massupdate'                => false,
            'no_default'                => false,
            'comments'                  => '',
            'help'                      => '',
            'importable'                => 'true',
            'duplicate_merge'           => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited'                   => false,
            'reportable'                => true,
            'unified_search'            => false,
            'merge_filter'              => 'disabled',
            'pii'                       => false,
            'calculated'                => false,
            'len'                       => 36,
            'size'                      => '20',
            'options'                   => 'parent_type_display',
            'default'                   => '',
            'type_name'                 => 'parent_type',
            'id_name'                   => 'parent_id',
            'parent_type'               => 'record_type_display',
            'studio'                    => 'visible',
        ),
        'parent_type'          => array(
            'required'                  => false,
            'name'                      => 'parent_type',
            'vname'                     => 'LBL_PARENT_TYPE',
            'type'                      => 'parent_type',
            'massupdate'                => false,
            'no_default'                => false,
            'comments'                  => '',
            'help'                      => '',
            'importable'                => 'true',
            'duplicate_merge'           => 'enabled',
            'duplicate_merge_dom_value' => 1,
            'audited'                   => false,
            'reportable'                => true,
            'unified_search'            => false,
            'merge_filter'              => 'disabled',
            'pii'                       => false,
            'calculated'                => false,
            'len'                       => 255,
            'size'                      => '20',
            'dbType'                    => 'varchar',
            'studio'                    => 'hidden',
            'group'                     => 'parent_name',
        ),
        'parent_id'            => array(
            'required'                  => false,
            'name'                      => 'parent_id',
            'vname'                     => 'LBL_PARENT_ID',
            'type'                      => 'id',
            'massupdate'                => false,
            'no_default'                => false,
            'comments'                  => '',
            'help'                      => '',
            'importable'                => 'true',
            'duplicate_merge'           => 'enabled',
            'duplicate_merge_dom_value' => 1,
            'audited'                   => false,
            'reportable'                => true,
            'unified_search'            => false,
            'merge_filter'              => 'disabled',
            'pii'                       => false,
            'calculated'                => false,
            'len'                       => 36,
            'size'                      => '20',
        ),
        'party_contact'        => array(
            'name'         => 'party_contact',
            'type'         => 'link',
            'relationship' => 'party_contact',
            'module'       => 'Contacts',
            'bean_name'    => 'Contact',
            'source'       => 'non-db',
            'vname'        => 'LBL_PARTY_CONTACT',
        ),
        'party_account'        => array(
            'name'         => 'party_account',
            'type'         => 'link',
            'relationship' => 'party_account',
            'module'       => 'Accounts',
            'bean_name'    => 'Account',
            'source'       => 'non-db',
            'vname'        => 'LBL_PARTY_ACCOUNT',
        ),
        'party_listg_listings' => array(
            'name'         => 'party_listg_listings',
            'type'         => 'link',
            'relationship' => 'party_listg_listings',
            'module'       => 'Listg_Listings',
            'bean_name'    => 'Listg_Listings',
            'source'       => 'non-db',
            'vname'        => 'LBL_PARTY_PROPERTY',
        ),
        'party_loans_loans'    => array(
            'name'         => 'party_loans_loans',
            'type'         => 'link',
            'relationship' => 'party_loans_loans',
            'module'       => 'Loans_Loans',
            'bean_name'    => 'Loans_Loans',
            'source'       => 'non-db',
            'vname'        => 'LBL_PARTY_LOANS',
        ),
        'qualia_unique_hash'   => array(
            'name'            => 'qualia_unique_hash',
            'label'           => 'Qualia Unique ID',
            'type'            => 'varchar',
            'module'          => 'Party_RQ_Party',
            'mass_update'     => true,
            'required'        => false,
            'reportable'      => true,
            'audited'         => false,
            'importable'      => true,
            'readonly'        => true,
            'duplicate_merge' => false,
        ),
    ),
    'relationships'      => array(
    ),
    'optimistic_locking' => true,
    'unified_search'     => true,
    'full_text_search'   => true,
);

if (!class_exists('VardefManager')) {
}
VardefManager::createVardef('Party_RQ_Party', 'Party_RQ_Party', array('basic', 'team_security', 'assignable', 'taggable'));
