<?php

$dictionary["Contact"]["fields"]["unique_code"] = [
    "name"                     => "unique_code",
    "vname"                    => "LBL_UNIQUE_CODE",
    "type"                     => "varchar",
    "enforced"                 => "",
    "required"                 => false,
    "massupdate"               => false,
    "calculated"               => true,
    "formula"                  => "",
    "readonly"                 => true,
    "readonly_formula"         => "",
    "default"                  => null,
    "isnull"                   => true,
    "no_default"               => false,
    "comments"                 => "ID in the Qualia integration",
    "help"                     => "",
    "importable"               => "true",
    "duplicate_merge"          => "disabled",
    "merge_filter"             => "disabled",
    "duplicate_on_record_copy" => "no",
    "audited"                  => true,
    "reportable"               => true,
    "unified_search"           => false,
    "studio"                   => [
        "recordview"               => true,
        "wirelessdetailview"       => true,
        "listview"                 => true,
        "wirelesseditview"         => true,
        "wirelesslistview"         => true,
        "wireless_basic_search"    => true,
        "wireless_advanced_search" => true,
        "portallistview"           => true,
        "portalrecordview"         => true,
        "portaleditview"           => true,
    ],
];
