<?php
$dictionary['Order_RQ_Order']['fields']['ordertype_c'] =
array(
    'name'                      => 'ordertype_c',
    'label'                     => 'Order Type',
    'name'                      => 'ordertype_c',
    'vname'                     => 'Order Type',
    'type'                      => 'enum',
    'massupdate'                => true,
    'no_default'                => false,
    'comments'                  => '',
    'help'                      => '',
    'importable'                => 'true',
    'duplicate_merge'           => 'enabled',
    'duplicate_merge_dom_value' => 1,
    'audited'                   => false,
    'reportable'                => true,
    'unified_search'            => false,
    'merge_filter'              => 'disabled',
    'pii'                       => false,
    'calculated'                => false,
    'len'                       => 100,
    'size'                      => '20',
    'options'                   => 'order_type_list',
    'default'                   => null,
    'dependency'                => null,
);
