<?php

/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

$dictionary['Listg_Listings'] = array(
    'table'              => 'listg_listings',
    'audited'            => true,
    'activity_enabled'   => false,
    'duplicate_merge'    => true,
    'fields'             => array(
        'qualia_unique_hash' => array(
            'required'                  => false,
            'name'                      => 'qualia_unique_hash',
            'vname'                     => 'LBL_QUALIA_UNIQUE_HASH',
            'type'                      => 'varchar',
            'massupdate'                => false,
            'no_default'                => false,
            'comments'                  => 'Unique hash for order',
            'label'                     => 'LBL_QUALIA_UNIQUE_HASH',
            'help'                      => '',
            'importable'                => 'true',
            'duplicate_merge'           => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited'                   => false,
            'reportable'                => true,
            'unified_search'            => false,
            'merge_filter'              => 'disabled',
            'pii'                       => false,
            'default'                   => '',
            'full_text_search'          => array(
                'enabled'    => '0',
                'boost'      => '1',
                'searchable' => false,
            ),
            'calculated'                => false,
            'len'                       => '255',
            'size'                      => '20',
        ),
        'qualia_diff_hash'   => array(
            'required'                  => false,
            'name'                      => 'qualia_diff_hash',
            'vname'                     => 'LBL_QUALIA_DIFF_HASH',
            'type'                      => 'varchar',
            'massupdate'                => false,
            'no_default'                => false,
            'comments'                  => 'Diff hash for order',
            'label'                     => 'LBL_QUALIA_DIFF_HASH',
            'help'                      => '',
            'importable'                => 'true',
            'duplicate_merge'           => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited'                   => false,
            'reportable'                => true,
            'unified_search'            => false,
            'merge_filter'              => 'disabled',
            'pii'                       => false,
            'default'                   => '',
            'full_text_search'          => array(
                'enabled'    => '0',
                'boost'      => '1',
                'searchable' => false,
            ),
            'calculated'                => false,
            'len'                       => '255',
            'size'                      => '20',
        ),
        'county'             => array(
            'required'                  => false,
            'name'                      => 'county',
            'vname'                     => 'LBL_COUNTY',
            'type'                      => 'varchar',
            'massupdate'                => false,
            'no_default'                => false,
            'comments'                  => '',
            'help'                      => '',
            'importable'                => 'true',
            'duplicate_merge'           => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited'                   => false,
            'reportable'                => true,
            'unified_search'            => false,
            'merge_filter'              => 'disabled',
            'pii'                       => false,
            'default'                   => '',
            'full_text_search'          => array(
                'enabled'    => '0',
                'boost'      => '1',
                'searchable' => false,
            ),
            'calculated'                => false,
            'len'                       => '128',
            'size'                      => '20',
        ),
        'state'              => array(
            'required'                  => false,
            'name'                      => 'state',
            'vname'                     => 'LBL_STATE',
            'type'                      => 'varchar',
            'massupdate'                => false,
            'no_default'                => false,
            'comments'                  => '',
            'help'                      => '',
            'importable'                => 'true',
            'duplicate_merge'           => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited'                   => false,
            'reportable'                => true,
            'unified_search'            => false,
            'merge_filter'              => 'disabled',
            'pii'                       => false,
            'default'                   => '',
            'full_text_search'          => array(
                'enabled'    => '0',
                'boost'      => '1',
                'searchable' => false,
            ),
            'calculated'                => false,
            'len'                       => '128',
            'size'                      => '20',
        ),
        'city'               => array(
            'required'                  => false,
            'name'                      => 'city',
            'vname'                     => 'LBL_CITY',
            'type'                      => 'varchar',
            'massupdate'                => false,
            'no_default'                => false,
            'comments'                  => '',
            'help'                      => '',
            'importable'                => 'true',
            'duplicate_merge'           => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited'                   => false,
            'reportable'                => true,
            'unified_search'            => false,
            'merge_filter'              => 'disabled',
            'pii'                       => false,
            'default'                   => '',
            'full_text_search'          => array(
                'enabled'    => '0',
                'boost'      => '1',
                'searchable' => false,
            ),
            'calculated'                => false,
            'len'                       => '64',
            'size'                      => '20',
        ),
        'zip_code'           => array(
            'required'                  => false,
            'name'                      => 'zip_code',
            'vname'                     => 'LBL_ZIP_CODE',
            'type'                      => 'varchar',
            'massupdate'                => false,
            'no_default'                => false,
            'comments'                  => '',
            'help'                      => '',
            'importable'                => 'true',
            'duplicate_merge'           => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited'                   => false,
            'reportable'                => true,
            'unified_search'            => false,
            'merge_filter'              => 'disabled',
            'pii'                       => false,
            'default'                   => '',
            'full_text_search'          => array(
                'enabled'    => '0',
                'boost'      => '1',
                'searchable' => false,
            ),
            'calculated'                => false,
            'len'                       => '64',
            'size'                      => '20',
        ),
        'address2'           => array(
            'required'                  => false,
            'name'                      => 'address2',
            'vname'                     => 'LBL_ADDRESS2',
            'type'                      => 'varchar',
            'massupdate'                => false,
            'no_default'                => false,
            'comments'                  => '',
            'help'                      => '',
            'importable'                => 'true',
            'duplicate_merge'           => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited'                   => false,
            'reportable'                => true,
            'unified_search'            => false,
            'merge_filter'              => 'disabled',
            'pii'                       => false,
            'default'                   => '',
            'full_text_search'          => array(
                'enabled'    => '0',
                'boost'      => '1',
                'searchable' => false,
            ),
            'calculated'                => false,
            'len'                       => '128',
            'size'                      => '20',
        ),
        'address'            => array(
            'required'                  => false,
            'name'                      => 'address',
            'vname'                     => 'LBL_ADDRESS',
            'type'                      => 'varchar',
            'massupdate'                => false,
            'no_default'                => false,
            'comments'                  => '',
            'help'                      => '',
            'importable'                => 'true',
            'duplicate_merge'           => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited'                   => false,
            'reportable'                => true,
            'unified_search'            => false,
            'merge_filter'              => 'disabled',
            'pii'                       => false,
            'default'                   => '',
            'full_text_search'          => array(
                'enabled'    => '0',
                'boost'      => '1',
                'searchable' => false,
            ),
            'calculated'                => false,
            'len'                       => '128',
            'size'                      => '20',
        ),
    ),
    'indices'            => [
        [
            'name'   => 'index_qualia_unique_hash_index',
            'type'   => 'index',
            'fields' => array(
                'qualia_unique_hash',
            ),
        ],
        [
            'name'   => 'index_qualia_diff_hash_index',
            'type'   => 'index',
            'fields' => array(
                'qualia_diff_hash',
            ),
        ],
    ],
    'relationships'      => array(
    ),
    'optimistic_locking' => true,
    'unified_search'     => true,
    'full_text_search'   => true,
);

if (!class_exists('VardefManager')) {
}
VardefManager::createVardef('Listg_Listings', 'Listg_Listings', array('basic', 'team_security', 'assignable', 'taggable'));
